CREATE TABLE IF NOT EXISTS name_mappings (
	original_name TEXT PRIMARY KEY,
	new_name TEXT NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE name_mappings ADD COLUMN IF NOT EXISTS budget_name TEXT DEFAULT '';
ALTER TABLE name_mappings ADD COLUMN IF NOT EXISTS category_name TEXT DEFAULT '';
